import React, { useState } from 'react';
import { SessionExportData } from '../../../shared/types.js';
import { X, Download, FileText, Check, Copy, Sparkles, CheckCircle2, MessageSquare, ThumbsUp, Home } from 'lucide-react';

interface ExportModalProps {
  exportData: SessionExportData;
  isOpen: boolean;
  onClose: () => void;
  onNewSession?: () => void;
}

// Generate CSV client-side with formula injection protection
function generateClientCSV(exportData: SessionExportData): string {
  const sanitizeCell = (val: string): string => {
    let clean = (val || '').replace(/"/g, '""');
    if (/^[=+\-@\t\r]/.test(clean)) {
      clean = "'" + clean;
    }
    return `"${clean}"`;
  };

  const headers = ['ID', 'Question', 'Slide / Section', 'Upvotes', 'Pinned', 'Status', 'Created Time', 'Resolved Time'];
  const rows = exportData.questions.map((q) => {
    const createdStr = new Date(q.createdAt).toISOString();
    const resolvedStr = q.resolvedAt ? new Date(q.resolvedAt).toISOString() : '';
    const slideStr = q.slideTag || 'None';
    return [
      q.id,
      sanitizeCell(q.text),
      sanitizeCell(slideStr),
      q.upvotes,
      q.isPinned ? 'Yes' : 'No',
      q.status,
      createdStr,
      resolvedStr,
    ].join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

// Generate Markdown summary client-side
function generateClientMarkdown(exportData: SessionExportData): string {
  const { room, questions, stats } = exportData;
  const dateStr = new Date(room.createdAt).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const resolved = questions.filter((q) => q.status === 'resolved');
  const pending = questions.filter((q) => q.status !== 'resolved');

  let md = `# Lecture Q&A Summary: ${room.topic}\n\n`;
  md += `**Date:** ${dateStr}  \n`;
  md += `**Room Code:** \`${room.code}\`  \n`;
  md += `**Duration:** ~${stats.durationMinutes} minutes  \n`;
  md += `**Total Questions:** ${stats.totalQuestions}  \n`;
  md += `**Total Upvotes:** ${stats.totalUpvotes}  \n`;
  md += `**Answered Questions:** ${stats.resolvedCount} / ${stats.totalQuestions}\n\n`;

  md += `## 🎙️ Answered Questions (${resolved.length})\n\n`;
  if (resolved.length === 0) {
    md += `*No questions were marked as resolved during this session.*\n\n`;
  } else {
    resolved.forEach((q, idx) => {
      const slide = q.slideTag ? ` \`[${q.slideTag}]\`` : '';
      const pinBadge = q.isPinned ? ' 📌 *(Pinned)*' : '';
      md += `${idx + 1}. **${q.text}**${slide}${pinBadge}\n`;
      md += `   - **Upvotes:** ${q.upvotes} | **Submitted:** ${new Date(q.createdAt).toLocaleTimeString()}\n\n`;
    });
  }

  md += `## 📋 Unaddressed Questions (${pending.length})\n\n`;
  if (pending.length === 0) {
    md += `*All student questions were successfully addressed!*\n\n`;
  } else {
    pending.forEach((q, idx) => {
      const slide = q.slideTag ? ` \`[${q.slideTag}]\`` : '';
      const pinBadge = q.isPinned ? ' 📌 *(Pinned)*' : '';
      md += `${idx + 1}. ${q.text}${slide}${pinBadge}\n`;
      md += `   - **Upvotes:** ${q.upvotes} | **Status:** ${q.status}\n\n`;
    });
  }

  md += `---\n*Generated by PulseQ — Classroom Real-Time Q&A HUD*\n`;
  return md;
}

// Download blob helper
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export const ExportModal: React.FC<ExportModalProps> = ({
  exportData,
  isOpen,
  onClose,
  onNewSession,
}) => {
  const [copiedMd, setCopiedMd] = useState(false);

  if (!isOpen) return null;

  const { room, stats, questions } = exportData;
  const safeTopic = (room.topic || 'Class').replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 30);

  const handleDownloadCSV = () => {
    try {
      const csv = generateClientCSV(exportData);
      downloadFile(csv, `${safeTopic}_${room.code}_QnA.csv`, 'text/csv');
    } catch (err) {
      console.warn('Fallback to server CSV export:', err);
      window.location.href = `/api/rooms/${room.code}/export/csv`;
    }
  };

  const handleDownloadMD = () => {
    try {
      const md = generateClientMarkdown(exportData);
      downloadFile(md, `${safeTopic}_${room.code}_Summary.md`, 'text/markdown');
    } catch (err) {
      console.warn('Fallback to server MD export:', err);
      window.location.href = `/api/rooms/${room.code}/export/md`;
    }
  };

  const handleCopyMarkdown = async () => {
    try {
      const md = generateClientMarkdown(exportData);
      await navigator.clipboard.writeText(md);
      setCopiedMd(true);
      setTimeout(() => setCopiedMd(false), 2500);
    } catch (err) {
      console.error('Failed to copy markdown:', err);
    }
  };

  const handleFinishAndReturn = () => {
    if (onNewSession) {
      onNewSession();
    } else {
      onClose();
    }
  };

  const resolvedPercent = stats.totalQuestions > 0
    ? Math.round((stats.resolvedCount / stats.totalQuestions) * 100)
    : 0;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-xl bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl p-6 sm:p-8">
        {/* Close Button — Returns to Main Screen */}
        <button
          onClick={handleFinishAndReturn}
          className="absolute top-5 right-5 p-2 text-slate-400 hover:text-slate-100 hover:bg-slate-800 rounded-full transition"
          aria-label="Close and return to main screen"
          title="Return to main screen"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Title */}
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-slate-100">Session Completed</h3>
            <p className="text-xs text-slate-400">{room.topic} &bull; Room <span className="font-mono font-semibold text-slate-300">{room.code}</span></p>
          </div>
        </div>

        {/* Metrics Grid */}
        <div className="grid grid-cols-3 gap-3 my-6">
          <div className="bg-slate-950 border border-slate-800/80 rounded-2xl p-3.5 text-center">
            <div className="flex items-center justify-center gap-1.5 text-slate-400 text-xs mb-1">
              <MessageSquare className="w-3.5 h-3.5" /> Doubts Asked
            </div>
            <span className="text-2xl font-extrabold text-slate-100">{stats.totalQuestions}</span>
          </div>

          <div className="bg-slate-950 border border-slate-800/80 rounded-2xl p-3.5 text-center">
            <div className="flex items-center justify-center gap-1.5 text-indigo-400 text-xs mb-1">
              <ThumbsUp className="w-3.5 h-3.5" /> Total Upvotes
            </div>
            <span className="text-2xl font-extrabold text-indigo-400">{stats.totalUpvotes}</span>
          </div>

          <div className="bg-slate-950 border border-slate-800/80 rounded-2xl p-3.5 text-center">
            <div className="flex items-center justify-center gap-1.5 text-emerald-400 text-xs mb-1">
              <Sparkles className="w-3.5 h-3.5" /> Resolved
            </div>
            <span className="text-2xl font-extrabold text-emerald-400">{resolvedPercent}%</span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="space-y-3 mb-6">
          <button
            onClick={handleDownloadCSV}
            className="w-full flex items-center justify-between p-4 bg-slate-950 hover:bg-slate-800/60 border border-slate-800 hover:border-slate-700 rounded-2xl transition group text-left"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-blue-500/10 text-blue-400 flex items-center justify-center group-hover:scale-105 transition">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <div className="font-semibold text-slate-100 text-sm">Download Spreadsheet (CSV)</div>
                <div className="text-xs text-slate-400">Full log with questions, slide numbers, upvotes & timestamps</div>
              </div>
            </div>
            <Download className="w-5 h-5 text-slate-400 group-hover:text-blue-400 transition" />
          </button>

          <button
            onClick={handleDownloadMD}
            className="w-full flex items-center justify-between p-4 bg-slate-950 hover:bg-slate-800/60 border border-slate-800 hover:border-slate-700 rounded-2xl transition group text-left"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-purple-500/10 text-purple-400 flex items-center justify-center group-hover:scale-105 transition">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <div className="font-semibold text-slate-100 text-sm">Download Markdown Summary (.md)</div>
                <div className="text-xs text-slate-400">Formatted documentation ready for Notion, Canvas, or GitHub</div>
              </div>
            </div>
            <Download className="w-5 h-5 text-slate-400 group-hover:text-purple-400 transition" />
          </button>

          <button
            onClick={handleCopyMarkdown}
            className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-slate-800/80 hover:bg-slate-700 text-slate-200 text-sm font-medium rounded-xl transition active:scale-98"
          >
            {copiedMd ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span className="text-emerald-300 font-semibold">Copied Summary to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-slate-400" />
                <span>Copy Markdown Summary to Clipboard</span>
              </>
            )}
          </button>
        </div>

        {/* Footer with Return to Main Screen Button */}
        <div className="flex items-center justify-between pt-3 border-t border-slate-800/60">
          <span className="text-xs text-slate-400">
            {questions.length} total questions logged
          </span>

          <button
            onClick={handleFinishAndReturn}
            className="flex items-center gap-1.5 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-xl transition active:scale-95 shadow-md shadow-indigo-600/25"
          >
            <Home className="w-3.5 h-3.5" />
            <span>Return to Main Screen</span>
          </button>
        </div>
      </div>
    </div>
  );
};
