import { SessionExportData, Question } from '../../shared/types.js';

// Sanitize cell values against formula injection (CWE-1236)
function sanitizeCell(val: string): string {
  let clean = val.replace(/"/g, '""');
  if (/^[=+\-@\t\r]/.test(clean)) {
    clean = "'" + clean;
  }
  return `"${clean}"`;
}

export function generateClientCSV(exportData: SessionExportData): string {
  const headers = ['ID', 'Question', 'Slide / Section', 'Upvotes', 'Pinned', 'Status', 'Created Time', 'Resolved Time'];
  const rows = exportData.questions.map((q) => {
    const createdStr = new Date(q.createdAt).toISOString();
    const resolvedStr = q.resolvedAt ? new Date(q.resolvedAt).toISOString() : '';
    const slideStr = q.slideTag || 'None';
    return [
      q.id,
      sanitizeCell(q.text),
      sanitizeCell(slideStr),
      q.upvotes,
      q.isPinned ? 'Yes' : 'No',
      q.status,
      createdStr,
      resolvedStr,
    ].join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

export function generateClientMarkdown(exportData: SessionExportData): string {
  const { room, questions, stats } = exportData;
  const dateStr = new Date(room.createdAt).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const resolved = questions.filter((q) => q.status === 'resolved');
  const pending = questions.filter((q) => q.status !== 'resolved');

  let md = `# Lecture Q&A Summary: ${room.topic}\n\n`;
  md += `**Date:** ${dateStr}  \n`;
  md += `**Room Code:** \`${room.code}\`  \n`;
  md += `**Duration:** ~${stats.durationMinutes} minutes  \n`;
  md += `**Total Questions:** ${stats.totalQuestions}  \n`;
  md += `**Total Upvotes:** ${stats.totalUpvotes}  \n`;
  md += `**Answered Questions:** ${stats.resolvedCount} / ${stats.totalQuestions}\n\n`;

  md += `## 🎙️ Answered Questions (${resolved.length})\n\n`;
  if (resolved.length === 0) {
    md += `*No questions were marked as resolved during this session.*\n\n`;
  } else {
    resolved.forEach((q, idx) => {
      const slide = q.slideTag ? ` \`[${q.slideTag}]\`` : '';
      const pinBadge = q.isPinned ? ' 📌 *(Pinned)*' : '';
      md += `${idx + 1}. **${q.text}**${slide}${pinBadge}\n`;
      md += `   - **Upvotes:** ${q.upvotes} | **Submitted:** ${new Date(q.createdAt).toLocaleTimeString()}\n\n`;
    });
  }

  md += `## 📋 Unaddressed Questions (${pending.length})\n\n`;
  if (pending.length === 0) {
    md += `*All student questions were successfully addressed!*\n\n`;
  } else {
    pending.forEach((q, idx) => {
      const slide = q.slideTag ? ` \`[${q.slideTag}]\`` : '';
      const pinBadge = q.isPinned ? ' 📌 *(Pinned)*' : '';
      md += `${idx + 1}. ${q.text}${slide}${pinBadge}\n`;
      md += `   - **Upvotes:** ${q.upvotes} | **Status:** ${q.status}\n\n`;
    });
  }

  md += `---\n*Generated by PulseQ — Classroom Real-Time Q&A HUD*\n`;
  return md;
}

export function downloadBlobFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
